all: SQLParser.class XMLParser.class Database.class Table.class Record.class Field.class
SQLParser.class: SQLParser.java
	javac -d . -classpath . SQLParser.java
XMLParser.class: XMLParser.java
	javac -d . -classpath . XMLParser.java
Database.class: Database.java
	javac -d . -classpath . Database.java
Table.class: Table.java
	javac -d . -classpath . Table.java
Record.class: Record.java
	javac -d . -classpath . Record.java
Field.class: Field.java
	javac -d . -classpath . Field.java
